CREATE TABLE USER_DATA
(
    USER_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_EMAIL VARCHAR2(255) NOT NULL,
    USER_PASSWORD VARCHAR2(255) NOT NULL,
    USER_AGE NUMBER NOT NULL,
    USER_ADDRESS VARCHAR2(50) NOT NULL,
    USER_GENDER VARCHAR2(50) NOT NULL,
    USER_ROLE VARCHAR2(50) NOT NULL
)