CREATE TABLE CALORIE_DATA
(
    CALORIE_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    CALORIE_COUNT NUMBER NOT NULL,
    CALORIE_UPDATED_DT TIMESTAMP NOT NULL,
    CALORIE_FOOD_TYPE VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL
)