export const CALORIE_COUNT="CALORIE_COUNT";
export const CALORIE_ID="CALORIE_ID";
export const USER_ID="USER_ID";
export const CALORIE_FOOD_TYPE="CALORIE_FOOD_TYPE";
export const CALORIE_UPDATED_DT="CALORIE_UPDATED_DT";
export const CALORIE="CALORIE";

export const SET_CALORIES="SET_CALORIES";
export const LOAD_CALORIES="LOAD_CALORIES";
export const SAVE_CALORIE="SAVE_CALORIE";
export const SAVE_CALORIE_SUCCESS="SAVE_CALORIE_SUCCESS";
export const SAVE_CALORIE_FAILURE= "SAVE_CALORIE_FAILURE";
export const GET_CALORIES_FAILURE= "GET_CALORIES_FAILURE";
export const UPDATE_CALORIE= "UPDATE_CALORIE";
export const DELETE_CALORIE= "DELETE_CALORIE";
